### ISSUE TITLE
Error 500 when loading in iFrame

### ISSUE THREAD

**Issue by mattti** [rmountjoy92/DashMachine#79]
After the update to 0.5:
When click on a card that is configured with `open_in = iframe`, i receive error 500 in the browser.
The log shows:

```
Traceback (most recent call last):

File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
return original_handler(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
TypeError: app_view() missing 1 required positional argument: 'app_id'
[2020-03-29 18:21:54,330] ERROR in app: Exception on /app_view?5 [GET]
```
The generated URL looks like this: `http://10.10.10.10:5000/app_view%3F5`
The cards worked as expected in the previous version. 

The same cards work fine if I select another `open_in` type.

**Comment by billyjacoby** [comment]
I'm having this same error. It doesn't work with local IPs or even public facing URLs
