### ISSUE TITLE
[version 0.6] Pihole module seems broken in v0.6

### ISSUE THREAD

**Issue by hoferbeck** [rmountjoy92/DashMachine#180]
Hello!

Firstly thanks for you work!
I found this project through r/selfhosted
now to the issue

For me the Pihole data source in v0.6 seems broken, its loading without a end
but i can switch the docker image to lastest (same mounts etc.) and then it work without any changes

Do I have to change something in the config to work with 0.6?

I also made a pastbin with my config [here](https://pastebin.com/XtBTdc06)
when I look in the docker logs in find the error: AttributeError: 'Platform' object has no attribute 'pihole'
[pastbin for docker logs](https://pastebin.com/AqXNxkBy)
BR

**Comment by jvteleco** [comment]
Hi, I installed yesterday the beta v0.6 and also had this error. I installed DashMachine via python3 (not docker).
I think I found the issue with the pihole error. I have created a fork of the file, not sure if it is the correct way.
You can have a look and if you want to try it, download it:
https://github.com/rmountjoy92/DashMachine/blob/96e5891238a095c0936229b9a3ed9257aec9c8eb/dashmachine/platform/pihole.py

**Comment by hoferbeck** [comment]
Hi @jvteleco Thx for me it also works. I tested with a vm on my windows pc
The Problem is its running at the moment on my main machine with docker. 
But I think you can make a PR and try to merge your changes :)

 BR
